### ISSUE TITLE
Feature request: profile name in OSX Keychain Item Name

### ISSUE THREAD

**Issue by simpsora** [sj26/awscli-keyring#2]
In the OSX Keyring implementation, keychain items are named `awscli:key` and `awscli:secret`.  It would be nice if the profile name was included in the item name, so they could be differentiated (e.g. in Keychain Access).

**Comment by simpsora** [comment]
This would probably be a breaking change for existing users, unless you could migrate their items.

**Comment by sj26** [comment]
They should be differentiable by account, which is the profile name.

**Comment by simpsora** [comment]
Yes, you can see the account if you drill into the individual item.  Here's the issue I was thinking of:

![screen shot 2015-07-10 at 11 33 53](https://cloud.githubusercontent.com/assets/735585/8610603/9bd66cb2-26f7-11e5-98ac-f7ae0865588d.png)

**Comment by sj26** [comment]
![screenshot 2015-07-10 11 38 01](https://cloud.githubusercontent.com/assets/14028/8610640/2f9d6d24-26f8-11e5-8aed-cf84131bf6ee.png)

**Comment by sj26** [comment]
That's kinda just how Keychain works, I'm afraid:

![screenshot 2015-07-10 11 39 21](https://cloud.githubusercontent.com/assets/14028/8610666/9a9f2cca-26f8-11e5-9ce6-fea2047fe487.png)

**Comment by simpsora** [comment]
My suggestion would be to pass in the profile as part of the `service` parameter to the keyring library's methods:

```
keyring.set_password("awscli:key-" + profile, profile, key)
```

It's not a big deal, but if you had a lot of them, there's no easy way to differentiate them in the list.

**Comment by lox** [comment]
Keychain actually supports a label, for exactly this purpose.
