### ISSUE TITLE
Keyring uses `security` command on OSX for Keychain access

### ISSUE THREAD

**Issue by lox** [sj26/awscli-keyring#3]
You guys might be aware, but I thought I'd point out that the keyring python library just acts as a wrapper to `/usr/bin/security`, which once whitelisted (in my experience most people press "Always Allow" the first time), will allow any process running as your user to access your keychain entries. 

Unless I've missed something, the entries get added to your login keychain, which means that for most practical purposes storing aws credentials this way isn't any better than plaintext in `~/.aws/credentials` with limited permissions (provided you have FileVault turned on).

Have I missed something? What attacks are prevented by storing credentials this way?

**Comment by pda** [comment]
Related: https://github.com/pda/aws-keychain/pull/13 (this slightly improves the situation for aws-keychain).
Unfortunately Python's keyring library [doesn't support the `-T ""` option yet](https://bitbucket.org/kang/python-keyring-lib/src/b2e88501a6a9bc7f1c7c230a6431ac0860ff4e50/keyring/backends/OS_X.py?at=default#OS_X.py-47).
Also worth noting that whitelisting is per-item, and that without that `-T ""` option the creator is whitelisted by default.

**Comment by lox** [comment]
Imma close this one ❤️
